apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: niximgs
build:
  artifacts:
    - custom:
        buildCommand: wharf skaffold build
      image: ghcr.io/shikanime-labs/niximgs/jellyfin
    - custom:
        buildCommand: wharf skaffold build
      image: ghcr.io/shikanime-labs/niximgs/mlflow
    - custom:
        buildCommand: wharf skaffold build
      image: ghcr.io/shikanime-labs/niximgs/postgresql
    - custom:
        buildCommand: wharf skaffold build
      image: ghcr.io/shikanime-labs/niximgs/radarr
    - custom:
        buildCommand: wharf skaffold build
      image: ghcr.io/shikanime-labs/niximgs/sonarr
    - custom:
        buildCommand: wharf skaffold build
      image: ghcr.io/shikanime-labs/niximgs/syncthing
    - custom:
        buildCommand: wharf skaffold build
      image: ghcr.io/shikanime-labs/niximgs/vaultwarden
    - custom:
        buildCommand: wharf skaffold build
      image: ghcr.io/shikanime-labs/niximgs/whisparr
