name: Commands
permissions:
  contents: read
  id-token: write
jobs:
  gh:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.actions.listRepoWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            for (const run of data.workflow_runs) {
              if (run.status === 'queued' || run.status === 'in_progress') {
                await github.rest.actions.cancelWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id,
                });
              }
            }
            await github.rest.actions.deleteWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
