name: Commands
permissions:
  contents: read
  id-token: write
  actions: write
jobs:
  gh:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
      actions: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.paginate(
              github.rest.actions.listRepoWorkflowRuns,
              { owner: context.repo.owner, repo: context.repo.repo }
            );
            for (const run of data.workflow_runs) {
              if (run.status === 'queued' || (run.status === 'in_progress' && run.id !== context.runId)) {
                await github.rest.actions.cancelWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id,
                });
              }
            }
