name: Integration
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  nix:
    uses: ./.github/workflows/nix.yaml
  skaffold:
    needs: [nix]
    uses: ./.github/workflows/skaffold.yaml
