name: Integration
on:
  pull_request:
    types: [closed]
  push:
    branches: [devlib-migration]
    paths:
      - .github/workflows/integration.yaml
      - .github/workflows/nix.yaml
      - .github/workflows/skaffold.yaml
  workflow_dispatch:
permissions:
  contents: read
jobs:
  nix:
    uses: ./.github/workflows/nix.yaml
  skaffold:
    needs: [nix]
    uses: ./.github/workflows/skaffold.yaml
