name: Nix
permissions:
  contents: read
jobs:
  setup-checks-jobs:
    name: Setup Checks Jobs
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps['setup-checks-jobs'].outputs.continue }}
      matrix: ${{ steps['setup-checks-jobs'].outputs.matrix }}
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.OPERATOR_APP_CLIENT_ID }}
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
          permission-contents: read
      - uses: shikanime-labs/actions/checkout@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-labs/actions/nix/setup@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - id: setup-checks-jobs
        uses: shikanime-labs/actions/nix/setup-checks-jobs@v9
  checks:
    name: Checks (${{ matrix.check }})
    if: needs['setup-checks-jobs'].outputs.continue == 'true'
    runs-on: ubuntu-latest
    needs: [setup-checks-jobs]
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs['setup-checks-jobs'].outputs.matrix) }}
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.OPERATOR_APP_CLIENT_ID }}
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
          permission-contents: read
      - uses: shikanime-labs/actions/checkout@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-labs/actions/nix/setup@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-labs/actions/nix/integration@v9
        with:
          check: ${{ matrix.check }}
  setup-packages-jobs:
    name: Setup Packages Jobs
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps['setup-packages-jobs'].outputs.continue }}
      matrix: ${{ steps['setup-packages-jobs'].outputs.matrix }}
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.OPERATOR_APP_CLIENT_ID }}
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
          permission-contents: read
      - uses: shikanime-labs/actions/checkout@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-labs/actions/nix/setup@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - id: setup-packages-jobs
        uses: shikanime-labs/actions/nix/setup-packages-jobs@v9
